CREATE DATABASE CURSO;
USE CURSO;
CREATE TABLE ALUMNOS (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE CHAR(100) NOT NULL,
TELEFONO INT NOT NULL, CORREO CHAR(100) NOT NULL);
SHOW DATABASES;
INSERT INTO ALUMNOS (NOMBRE, TELEFONO, CORREO) VALUES('JUAN HERNANDEZ', 52321123, 'juanhz@123.com');
UPDATE ALUMNOS SET TELEFONO=24244242,CORREO='juanhz@321.com' WHERE ID = 4;
DELETE FROM ALUMNOS WHERE ID = 1;
SELECT * FROM ALUMNOS;